spring.application.name=yukti-website
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# database connection details
#spring.datasource.url=jdbc:postgresql://localhost:5432/yukti_website
#spring.datasource.username=
#spring.datasource.password=

spring.datasource.url=
#spring.datasource.username=
#spring.datasource.password=
spring.datasource.hikari.maximum-pool-size=10


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Ratelimiter configuration
resilience4j.ratelimiter.instances.workshopRegistration.limit-for-period=20
resilience4j.ratelimiter.instances.workshopRegistration.limit-refresh-period=1m
resilience4j.ratelimiter.instances.workshopRegistration.timeout-duration=0